In [1]:
import xarray as xr
import numpy as np
import pandas as pd

In [5]:
dt=xr.open_dataset("Datasets/f.e11.F1850C5CN.f09_f09.001.clm2.h0.RAIN.230001-239912.nc")
rain=dt['RAIN']

db=rain.loc['2301-01-01':'2302-01-01']
print(rain.shape)

(1200, 192, 288)


In [6]:
db.time.values


array([cftime.DatetimeNoLeap(2301, 1, 1, 0, 0, 0, 0, 5, 1),
       cftime.DatetimeNoLeap(2301, 2, 1, 0, 0, 0, 0, 1, 32),
       cftime.DatetimeNoLeap(2301, 3, 1, 0, 0, 0, 0, 1, 60),
       cftime.DatetimeNoLeap(2301, 4, 1, 0, 0, 0, 0, 4, 91),
       cftime.DatetimeNoLeap(2301, 5, 1, 0, 0, 0, 0, 6, 121),
       cftime.DatetimeNoLeap(2301, 6, 1, 0, 0, 0, 0, 2, 152),
       cftime.DatetimeNoLeap(2301, 7, 1, 0, 0, 0, 0, 4, 182),
       cftime.DatetimeNoLeap(2301, 8, 1, 0, 0, 0, 0, 0, 213),
       cftime.DatetimeNoLeap(2301, 9, 1, 0, 0, 0, 0, 3, 244),
       cftime.DatetimeNoLeap(2301, 10, 1, 0, 0, 0, 0, 5, 274),
       cftime.DatetimeNoLeap(2301, 11, 1, 0, 0, 0, 0, 1, 305),
       cftime.DatetimeNoLeap(2301, 12, 1, 0, 0, 0, 0, 3, 335),
       cftime.DatetimeNoLeap(2302, 1, 1, 0, 0, 0, 0, 6, 1)], dtype=object)

In [7]:
da=db.resample(time='1D').interpolate('linear')
da[0:50,19,9]

<xarray.DataArray 'RAIN' (time: 50)>
array([2.13465963e-22, 2.14275718e-22, 2.15085473e-22, 2.15895229e-22,
       2.16704984e-22, 2.17514739e-22, 2.18324494e-22, 2.19134250e-22,
       2.19944005e-22, 2.20753760e-22, 2.21563515e-22, 2.22373270e-22,
       2.23183026e-22, 2.23992781e-22, 2.24802536e-22, 2.25612291e-22,
       2.26422047e-22, 2.27231802e-22, 2.28041557e-22, 2.28851312e-22,
       2.29661068e-22, 2.30470823e-22, 2.31280578e-22, 2.32090333e-22,
       2.32900089e-22, 2.33709844e-22, 2.34519599e-22, 2.35329354e-22,
       2.36139109e-22, 2.36948865e-22, 2.37758620e-22, 2.38568375e-22,
       2.31322961e-22, 2.24077547e-22, 2.16832132e-22, 2.09586718e-22,
       2.02341304e-22, 1.95095890e-22, 1.87850475e-22, 1.80605061e-22,
       1.73359647e-22, 1.66114233e-22, 1.58868819e-22, 1.51623404e-22,
       1.44377990e-22, 1.37132576e-22, 1.29887162e-22, 1.22641747e-22,
       1.15396333e-22, 1.08150919e-22])
Coordinates:
    lon      float32 11.25
    lat      float32 -72.09424


In [8]:
da.time.values

array([cftime.DatetimeNoLeap(2301, 1, 1, 0, 0, 0, 0, 5, 1),
       cftime.DatetimeNoLeap(2301, 1, 2, 0, 0, 0, 0, 6, 2),
       cftime.DatetimeNoLeap(2301, 1, 3, 0, 0, 0, 0, 0, 3),
       cftime.DatetimeNoLeap(2301, 1, 4, 0, 0, 0, 0, 1, 4),
       cftime.DatetimeNoLeap(2301, 1, 5, 0, 0, 0, 0, 2, 5),
       cftime.DatetimeNoLeap(2301, 1, 6, 0, 0, 0, 0, 3, 6),
       cftime.DatetimeNoLeap(2301, 1, 7, 0, 0, 0, 0, 4, 7),
       cftime.DatetimeNoLeap(2301, 1, 8, 0, 0, 0, 0, 5, 8),
       cftime.DatetimeNoLeap(2301, 1, 9, 0, 0, 0, 0, 6, 9),
       cftime.DatetimeNoLeap(2301, 1, 10, 0, 0, 0, 0, 0, 10),
       cftime.DatetimeNoLeap(2301, 1, 11, 0, 0, 0, 0, 1, 11),
       cftime.DatetimeNoLeap(2301, 1, 12, 0, 0, 0, 0, 2, 12),
       cftime.DatetimeNoLeap(2301, 1, 13, 0, 0, 0, 0, 3, 13),
       cftime.DatetimeNoLeap(2301, 1, 14, 0, 0, 0, 0, 4, 14),
       cftime.DatetimeNoLeap(2301, 1, 15, 0, 0, 0, 0, 5, 15),
       cftime.DatetimeNoLeap(2301, 1, 16, 0, 0, 0, 0, 6, 16),
       cftime.DatetimeNoLe

In [9]:
dt.RAIN[0:50,19,9].values


array([2.72679157e-10, 1.16937735e-23, 7.97161943e-22, 4.20483486e-22,
       1.40087043e-22, 1.33612651e-21, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 6.67081134e-24, 1.97029825e-22, 2.13465963e-22,
       2.38568375e-22, 3.56967827e-23, 2.77950466e-24, 2.98704107e-23,
       1.15627400e-21, 7.07698957e-22, 9.01167581e-25, 0.00000000e+00,
       0.00000000e+00, 1.31192630e-22, 4.36567553e-23, 0.00000000e+00,
       2.83287549e-21, 3.79124461e-21, 2.60258930e-21, 3.27950128e-22,
       2.66498913e-21, 7.74332980e-21, 2.93150889e-24, 0.00000000e+00,
       0.00000000e+00, 6.62633921e-22, 1.89564462e-22, 2.99630602e-22,
       8.73123568e-19, 3.63122469e-22, 0.00000000e+00, 0.00000000e+00,
       6.22609037e-23, 0.00000000e+00, 0.00000000e+00, 4.43861886e-20,
       9.19089534e-24, 1.08580204e-27, 2.29772384e-24, 1.56275041e-24,
       1.31331596e-22, 8.51799131e-22], dtype=float32)

In [10]:
indexofval=[15.5,45,74.5,105,135.5,166,196.5,227.5,258,288.5,319,349.5 ]
roundd=[]

In [11]:
for i in range(len(indexofval)):
    roundd.append(round(indexofval[i]))
roundd  

[16, 45, 74, 105, 136, 166, 196, 228, 258, 288, 319, 350]

In [12]:
len(db.values)
rain.shape

(1200, 192, 288)

In [13]:
db.values[1]

array([[9.1847360e-22, 9.1850420e-22, 9.1848683e-22, ..., 9.1847169e-22,
        9.1844977e-22, 9.1846946e-22],
       [2.4408642e-21, 2.2553205e-21, 2.3905738e-21, ..., 2.3756704e-21,
        2.5164159e-21, 2.6044729e-21],
       [6.5613331e-21, 6.0954592e-21, 5.8928096e-21, ..., 4.5848881e-21,
        4.7621891e-21, 5.8058539e-21],
       ...,
       [          nan,           nan,           nan, ...,           nan,
                  nan,           nan],
       [          nan,           nan,           nan, ...,           nan,
                  nan,           nan],
       [          nan,           nan,           nan, ...,           nan,
                  nan,           nan]], dtype=float32)

In [14]:
temp=[[np.nan for i in range(rain.shape[2])]for j in range(rain.shape[1])]

In [15]:
ans=[temp for i in range(365)]

In [16]:
count=0
for i in roundd:
    
    ans[i]=db.values[count].tolist()
    count=count+1
# print(roundd)


In [17]:
ans=np.array(ans)

In [18]:
ans[0]

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])